### ISSUE TITLE
Не открывается страница приложения.

### ISSUE THREAD

**Issue by DarcenRal** [DarcenRal/Diplom_1#1]
**Шаги для воспроизведения**:

- Склонировать данный репозиторий.
- Открыть проект в Intellij IDEA Ultimate Edition.
- Запустить Docker.
- В терминале IDEA выполнить команду docker-compose up.
- В другой вкладке терминала запустить приложение командой java -jar aqa-shop.jar --server.port=8080
- Открыть любой браузер.
- Ввести URL: http://localhost:8080/

**Ожидаемый результат**

Откроется страница приложения.

**Фактический результат**

Не удается получить доступ к сайту.

**Окружение**

Тестирование производилось в следующем окружении:

Windows 10 версия 19043.1466
java -version openjdk version "11.0.9.1" 2020-11-04
IntelliJ IDEA 2021.,3 (Ultimate Edition)

**Comment by Vladanna** [comment]
Добрый день!


Попробовала запустить ваше приложение, но не может стартовать. Падает с ошибкой
`2022-01-25 23:51:11.809 ERROR 22820 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'shopController' defined in URL [jar:file:/Users/ruamyl5/netology-diploma/Diplom_1_yakov/Artifacts/aqa-shop.jar!/BOOT-INF/classes!/ru/netology/shop/controller/ShopController.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'shopService' defined in URL [jar:file:/Users/ruamyl5/netology-diploma/Diplom_1_yakov/Artifacts/aqa-shop.jar!/BOOT-INF/classes!/ru/netology/shop/service/ShopService.class]: Unexpected exception during bean creation; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'spring.credit-gate.url' in value "${spring.credit-gate.url}"
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:787) ~[spring-beans-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
        at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:226) ~[spring-beans-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1358) ~[spring-beans-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1204) ~[spring-beans-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:557) ~[spring-beans-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517) ~[spring-beans-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323) ~[spring-beans-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321) ~[spring-beans-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
      `


Подскажите в чем проблема?

**Comment by rohtuasad** [comment]
Приложение при старте не может найти конфигурационный файл application.properties.
Для того, чтобы он был найден, можно переместить его в одну папку с aqa-shop.jar, или использовать параметр запуска, указывающий местоположение конфигурационного файла.
https://www.baeldung.com/spring-properties-file-outside-jar
